apiVersion: v1
kind: Service
metadata:
  name: appaks
  namespace: namespace-workflow-1698413598129
spec:
  type: LoadBalancer
  selector:
    app: appaks
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080